### ISSUE TITLE
Create data model for tracked items

### ISSUE THREAD

**Issue by hahuang65** [BitSmithy/price_tracker#1]
We'll need a data model to be able to track items.

Things we'll want to accommodate:
1) Being able to track a canonical item (e.g. URLs from Amazon and Walmart might differ, but it should be represented as the same item in our database)
2) Be able to refer to a canonical item from multiple representations of that item (e.g. we should be able to know, for a given item, that it's priced at X for Walmart and Y for Amazon)

Let's just focus on the model and database schemas for this ticket.
Also, let's not worry about the actual external retailers yet for this ticket.

**Comment by aghalarp** [comment]
After doing some brief research across some of the more popular online retailers (Amazon, Walmart, Best Buy, etc.), I believe we need to be concerned about two types of product identification numbers:
1. UPC
2. SKU

**UPC** numbers are identification numbers that are unique to the given product. They have to be registered and paid for by the product manufacturer. As such, we can use the UPC number to search for a given product across multiple online retailers. I checked a few APIs (Amazon, Walmart, and Best Buy), and they all do seem to offer some way to search for a product by UPC.

**SKU** numbers are identification numbers that are used internally by the retailer to uniquely identify the product. Not every retailer will actually use the term “SKU” - rather, they might employ their own term for this (Amazon uses ASIN, Walmart uses ItemID). The general point being, each retailer will likely employ some type of internal identification number for their products. This is important to note, because some APIs might require us to lookup an item via its SKU rather than UPC number.

I created an initial ERD draft of the data model for the entire price_tracker app, based on the preliminary information from all the data model related tickets. Directly related to this ticket are the **CanonicalProduct** and **RetailerProduct** entities (I suck at naming things). An argument can be made to combine these two into a single entity and use the upc and sku to form a compound key - but I wasn't sure if that was the way to go. What do you think?

![pricetracker erd](https://user-images.githubusercontent.com/5334478/49306196-95807000-f49f-11e8-8ae7-222b682c5738.png)

**Comment by hahuang65** [comment]
Completed with https://github.com/BitSmithy/price_tracker/pull/18
